name: Build and Deploy Endpoints Azure Function

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: site-endpoints # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./src/Cloud/Functions/Endpoints/Site.Endpoints"
  SOLUTION_NAME: "Site.Endpoints.sln" # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: "3.1.x" # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

        # BUILD
      - name: Build Endpoints Project
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: dotnet build ${{ env.SOLUTION_NAME }} --configuration Release --output ./output

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
          publish-profile: ${{ secrets.SITE_ENDPOINTS_PUBLISH_PROFILE }}
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
