name: Build and Deploy Scheduler Azure Function 

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: site-scheduler  # set this to your application's name
  SOLUTION_FILE_PATH: "src/Cloud/Functions/Scheduler/Site.Scheduler"
  SOLUTION_NAME: 'Site.Scheduler.sln'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.x'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.SOLUTION_FILE_PATH }}'
        dotnet build ${{ env.SOLUTION_NAME }} --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.SOLUTION_FILE_PATH }}/output'
        publish-profile: ${{ secrets.SITE_SCHEDULER_PUBLISH_PROFILE }}

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples